version: '3.9'

networks:
    postgres_net:
        driver: bridge

volumes:
    postgres_data:
    pgadmin_data:
        
services:
    postgres:
        image: postgres:17.7
        container_name: postgres17
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${POSTGRES_DB:-postgres}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_password}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        networks:
            - postgres_net
            
    pgadmin:
        image: dpage/pgadmin4:9.10
        container_name: pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin_password}
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - postgres_net
        depends_on:
            - postgres

# -------------------------------
# Start:
# docker-compose up -d
# -------------------------------
# Access to Postgres:
# localhost:5432
# Username: postgres
# Password: postgres_password
# -------------------------------
# Access to PgAdmin:
# URL: http://localhost:5050
# EMAIL: pgadmin4@pgadmin.org
# Password: pgadmin_password
# -------------------------------
# Connect to Postgres from PgAdmin
# Host name/address: postgres17
# Port: 5432
# Maintenance DB: postgres
# Username: postgres
# Password: postgres_password
# -------------------------------
# Stop containers:
# docker-compose stop
# -------------------------------
# Start containers
# docker-compose start
# -------------------------------
# Stop and delete containers and network:
# docker-compose down
# -------------------------------